### ISSUE TITLE
Linting Setup

### ISSUE THREAD

**Issue by sakulstra** [e-Ray/web_platform#3]
### Setup Linting (eslint)
To get a end product we can continue with, we want you to maintain a well defined code-style.
In prior projects we used airbnb code-style like suggested in the meteor guide https://guide.meteor.com/code-style.html, https://github.com/airbnb/javascript ... You can go with this or some other code-style :) Just pick one and stay consistent.

**Comment by kwallaschek** [comment]
Finally added Airbnb to CodeClimate.

**Comment by sakulstra** [comment]
you can merge #37 and add it before your travis test step, so that the tests/build only runs when at least the linting succeeded
