### ISSUE TITLE
Detail Chart Component

### ISSUE THREAD

**Issue by sakulstra** [e-Ray/web_platform#33]
Refinement of #5 

Create a modular component for detail pages which are able to display:
- a title
- a unit for y-axis
- a timespan selector (last 1h, last 1d, last 1w, custom)
  - when custom is selected there should appear two additional date inputs where you can select a from-to time-span
- the labels on x axis should be rendered in a sane way (if time-span is e.g. a year, it's sufficient to have labels for each month, if time-span is only 1h there can be a label for each data point)

### Result
A component could look like this and should render and provider data to a child `<Chart:or whatever you called it>` component
```js
<GenericSensorPage
  title={title}
  unit={unit}
/>
```
and be instantiated like this
```js
const PerformancePage = () => (
  <GenericSensorPage
    title="Leistung"
    unit="W"
  />
   <div>Some additional text and content for this page</div>
  </GenericSensorPage>
)

export default PerformancePage;
```

![photo_2017-01-03_18-30-14](https://cloud.githubusercontent.com/assets/4396533/21616675/b9a23158-d1e2-11e6-9cfd-0c528cef712d.jpg)

### Hints
You could/should create a HOC (https://medium.com/@franleplant/react-higher-order-components-in-depth-cf9032ee6c3e#.n2x1lkmcj) for the data-fetching. You could use https://github.com/arunoda/react-komposer if you don' want to create the HOC yourself.

**Comment by kwallaschek** [comment]
Problem, dass der graph nicht neu geladen hat gelöst durch 
sensor.js: getData(range) im handler().

**Comment by AnjaKirchhoefer** [comment]
- Eray auf das zugegriffen wird, ist noch gehardcoded -> wegen Benutzerstudie
- Auf dem Dashboard wird am Anfang noch nichts angezeigt, erst wenn die jeweilige DetailPage aufgerufen wurde.
- timeSpan.customDayTo ändert sich bei Berechnung des Tages der als nächstes ausgelesen werden soll, obwohl dieser nicht zugewiesen wird.
